version: '3.9'

services:
  vector-agent:
    depends_on:
      - vector-aggregator
      - rustlogger
    image: timberio/vector:0.24.1-debian
    volumes:
      - ./vector-agent/:/etc/vector/
    container_name: vector-agent

  vector-aggregator:
    depends_on:
      - loki
      - influxdb
    restart: always
    image: timberio/vector:0.24.1-debian
    volumes:
      - ./vector-aggregator/:/etc/vector/
    container_name: vector-aggregator 
  
  rustlogger:
    # image: rustlogger
    build:
      context: ./
      dockerfile: ./dockerfile
    restart: always
    container_name: rustlogger
    environment:
      - RUST_LOG=trace

  grafana:
    image: grafana/grafana-oss
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_AUTH_DISABLE_LOGIN_FORM=true.
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin

  loki:
    image: grafana/loki:2.6.0
    container_name: loki
    ports:
      - "3100:3100"

  influxdb: 
    image: influxdb
    restart: always
    ports:
      - "8086:8086"
    container_name: influxdb
    environment:
      - INFLUXDB_DB=vector-database
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=username
      - DOCKER_INFLUXDB_INIT_PASSWORD=password
      - DOCKER_INFLUXDB_INIT_ORG=vector-org
      - DOCKER_INFLUXDB_INIT_BUCKET=vector-bucket
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=pOqxyhvAj-0ULQwlmo3VVX9FKTcthQZrMBkhEbn3vteeHPFWA4U9qp8WuAsE6cp7JEVgf6J6YvPVUJqGe0WCMQ==