apiVersion: 1

datasources:
  - name: Timescaledb - Vector playing
    uid: 1
    type: postgres
    url: timescaledb:5432
    user: postgres
    secureJsonData: 
      password: 'postgres'
    jsonData:
      sslmode: 'disable'
      timescaledb: true

  - name: Loki - Vector playing
    uid: 2
    type: loki
    access: proxy
    url: http://loki:3100
    default: true
