apiVersion: 1

datasources:
  - name: Influx - Vector playing
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    secureJsonData:
      token: "pOqxyhvAj-0ULQwlmo3VVX9FKTcthQZrMBkhEbn3vteeHPFWA4U9qp8WuAsE6cp7JEVgf6J6YvPVUJqGe0WCMQ=="
    jsonData:
      version: Flux
      organization: vector-org
      defaultBucket: vector-bucket
    uid: wMZlVr4Vz

  - name: Loki - Vector playing
    type: loki
    access: proxy
    url: http://loki:3100
    default: true
