[sources.in_logs]
type = "vector"
address = "0.0.0.0:6000"
version = "2"

[sources.in_metrics]
type = "vector"
address = "0.0.0.0:6001"
version = "2"

[sinks.out_logs]
type = "loki"
inputs = ["in_logs"]
endpoint = "http://loki:3100"
compression = "none"
encoding.codec = "json"
    [sinks.out_logs.labels]
    forwarder = "vector-aggregator"
    app = "{{ app }}"
    severity = "{{ severity }}"

[sinks.out_metrics]
type = "influxdb_metrics"
inputs = ["in_metrics"]
consistency = "any"
endpoint = "http://influxdb:8086/"
org = "vector-org"
bucket = "vector-bucket"
default_namespace = "aggregator"
token = "pOqxyhvAj-0ULQwlmo3VVX9FKTcthQZrMBkhEbn3vteeHPFWA4U9qp8WuAsE6cp7JEVgf6J6YvPVUJqGe0WCMQ=="