[sources.logs]
type = "docker_logs"
include_containers = [ "rustlogger-1" ]
docker_host = "http://host.docker.internal:2375"

# When everything is running, uncomment this block and add to the transforms.parse > inputs another item "logs3" and save the file, the vector
# will reload

# [sources.logs3]
# type = "docker_logs"
# include_containers = [ "rustlogger-3" ]
# docker_host = "http://host.docker.internal:2375"

[transforms.parse]
type = "remap"
inputs = ["logs"]
source = """
temp = .
. = {}
. = parse_json!(temp.message)
.ic_node = temp.container_name
.ic_subnet = "172.18.0.0/16"
.dc = "this should've reloaded"
.ipv4 = "172.18.0.0"
"""

[sinks.out_logs]
type = "loki"
inputs = ["parse"]
endpoint = "http://loki:3100"
compression = "none"
    [sinks.out_logs.labels]
    ic_node = "{{ ic_node }}"
    ic_subnet = "{{ ic_subnet }}"
    dc = "{{ dc }}"
    ipv4 = "{{ ipv4 }}"
    severity = "INFO"
    [sinks.out_logs.encoding]
    codec = "json"